async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
async function loadBooks(){const q=document.getElementById("search")?.value||"";const books=await api("/api/public/books?q="+encodeURIComponent(q));document.getElementById("booksGrid").innerHTML=books.map(b=>`<article class="book"><h3>${esc(b.title)}</h3><p class="muted">${esc(b.author)}</p><p>${esc(b.category||"General")}</p><p>Available: <b>${b.available_copies}</b></p><button onclick="borrow(${b.id})">Borrow</button></article>`).join("")||"<p>No books found.</p>"}
async function borrow(id){try{await api("/api/loans/borrow/"+id,{method:"POST"});alert("Book borrowed successfully. Due in 15 days.");loadBooks();loadDashboard()}catch(e){alert(e.message)}}
async function loadDashboard(){const m=await api("/api/auth/me");if(!m.user)return;document.getElementById("dashboard").classList.remove("hidden");document.getElementById("welcome").textContent=`Welcome, ${m.user.name} (${m.user.role})`;const loans=await api("/api/loans/mine");let html=`<div class="cards"><div class="stat">Role<b>${m.user.role}</b></div><div class="stat">Active books<b>${loans.filter(x=>!x.return_date).length}/5</b></div><div class="stat">Total fines<b>${loans.reduce((a,x)=>a+Number(x.fine||0),0)}</b></div></div><h3>Your loans</h3>`;html+=loans.map(l=>`<div class="book"><b>${esc(l.title)}</b><p>Due: ${l.due_date} • Fine: ${l.fine}</p>${!l.return_date?`<button onclick="renew(${l.id})">Renew</button><button class="ghost" onclick="returnBook(${l.id})">Return</button>`:"Returned"}</div>`).join("");if(m.user.role==="teacher")html+=`<h3>Teacher: request a new book</h3><form onsubmit="requestBook(event)"><input name="title" placeholder="Book title" required><input name="author" placeholder="Author" required><input name="reason" placeholder="Reason"><button>Send Request</button></form>`;document.getElementById("dash").innerHTML=html}
async function renew(id){try{await api("/api/loans/renew/"+id,{method:"POST"});alert("Renewed for 15 days.");loadDashboard()}catch(e){alert(e.message)}}
async function returnBook(id){try{await api("/api/loans/return/"+id,{method:"POST"});loadDashboard();loadBooks()}catch(e){alert(e.message)}}
async function requestBook(e){e.preventDefault();const f=new FormData(e.target);try{await api("/api/requests",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});alert("Request sent.");e.target.reset()}catch(x){alert(x.message)}}
async function logout(){await api("/api/auth/logout",{method:"POST"});location.reload()}
document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/api/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});location.hash="dashboard";loadDashboard()}catch(x){document.getElementById("loginMsg").textContent=x.message}}
document.getElementById("registerForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/api/auth/register",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});location.hash="dashboard";loadDashboard()}catch(x){document.getElementById("registerMsg").textContent=x.message}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
loadBooks();loadDashboard();setInterval(loadDashboard,60000);